### PR TITLE
Update README.md examples to work with latest rescript (11)

### PR DESCRIPTION
**Pull request by gaspard**

### CODE REVIEW

**Review by DZakh — APPROVED** [review]
Thanks, missed it when I updated API to remove trailing units 🤝

**Comment by gaspard** [comment]
Thanks for the library BTW (also exploring your express bindings) !

**Comment by DZakh** [comment]
Express bindings aren't mine :) I'm actually more into Fastify, but I haven't published anything yet. Although, I plan to develop https://github.com/DZakh/rescript-rest even more and add support for multiple backend frameworks.

**Comment by gaspard** [comment]
Yes, rescript-rest looks like an amazing project. Ping me if you want to team-up at some point to work on the server side of this !

**Comment by DZakh** [comment]
Sure 👌

**Pull request merged**
